### ISSUE TITLE
A version on crates.io ?

### ISSUE THREAD

**Issue by gilescope** [rust-lang/portable-simd#129]
I understand that the goal at some point is for this to be part of rust std lib, but at the moment the project seems to be useful enough to publish on crates io so that people can build on top of it. At the moment no one can publish a crate that depends on core simd. If it's done as a version below 1.0 then people will have no expectations of backward compatability.

This could lead to a lot more usage and thus we might iterate faster towards something that everyone's happy with.

**Comment by Lokathor** [comment]
The crate is kinda extra-unstable at the moment because each thing we add pokes a bit at the const generics and the compiler's intrinsics and so on. If you don't mind that then you can point your Cargo.toml at the git repo, even a particular commit, if you feel the need to use this immediately.

And the `wide` crate is still sitting there if you need something like this API but on Stable and/or on crates.io.

**Comment by workingjubilee** [comment]
We discussed this and we aren't doing this. We are just going to put this into libcore (see https://github.com/rust-lang/rust/pull/89167). Having two different versions is confusing, maintaining a crates.io release and keeping it in sync with potentially changes in two different repositories is annoying and easy to forget, and stdarch only did releases on crates.io for a short while.
