### ISSUE TITLE
Native vector width

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/portable-simd#218]
Assuming an algorithm vectorizes well (contains mostly aligned load/stores and vertical operations, with little swizzles, gather/scatter, trig, and other "complex" ops), it should perform best when using native-width SIMD instructions.

Unfortunately, finding out what is the native SIMD width for a given scalar type T is hairy for several reasons:

- There is no such thing as a single native vector size that can be simply divided by the scalar size to deduce the native SIMD width. For example, x86 CPUs that support AVX but not AVX2 have 256-bit SIMD for floats and 128-bit SIMD for integers.
- The native vector width may not be the widest available vector width. Some CPUs (most prominent example these days being lower-end AVX-512 chips) provide wide SIMD operations that are essentially emulated using narrower ALUs. Unsurprisingly, these CPUs perform best when directly using the underlying narrow SIMD operations. The problem is that although this information may be provided to the compiler as a "preferred vector width" hint, it is in general not known until runtime.
- "Scalable" instruction sets like ARM SVE have a native vector width that, by design, may not be known until runtime (although it may be provided as a compiler hint for better codegen).

Given that this problem is hairy, commonly encountered, important to optimal SIMD performance, and relatively self-contained, I think it would be best if `core::simd` provided its solution to it. This could take the form of...

- A faillible API for querying the suggested vector width at compile time when such a hint is available, e.g. `const fn preferred_width<T>() -> Option<usize>`.
- An (ideally) infaillible API for querying the native vector width at run time, e.g. `fn native_width<T>() -> usize`.
    * I say ideally infaillible as this would be most useful to users and I am sure that the info can be found at runtime. But I'm not sure if for all instruction sets it can be found without resorting to microbenchmarking or looking up the CPU model identifier in a hardware database. If not, `core::simd` may understandably not want to take the burden of maintaining either a HW database or a binding to someone else's database. In that case, the runtime API should be made faillible too.

One open question is the set of operations that must be natively supported before we consider a certain vector type to be natively supported. After all, lower-end AVX-512 CPUs have native 512-bit loads and stores and swizzles, it is only ALU operations that are non-native. In my opinion, loads, stores and basic ALU ops (add, sub, mul) are a minimum for a certain vector width to be considered native.

**Comment by bjorn3** [comment]
You can use the [multiversion](https://crates.io/crates/multiversion) crate to provide multiple versions of a function for each target feature. Each can then use a different vector width.

**Comment by HadrienG2** [comment]
I find that answer somewhat unsatisfactory for two reasons:

- `multiversion` requires me to explicitly list a set of hardware to optimize for and, in a `core::simd` explicit vectorization context, to know the right SIMD vector size for that hardware. All of this undermines portability, in the sense that codebases based on `multiversion` will only be optimized on hardware that the developer thought about. But my understanding is that one design goal of `core::simd` is to make it easier to write SIMD portable code that works "fairly well" on hardware that the original dev did not think about, and this is where the feature that I am proposing comes in handy.
- The set of target features that `multiversion` can dispatch on is not enough to decide on an optimal vector width, as evidenced by wide vector emulation on some hardware (see AVX-512 on low-end Intel chips, AVX on Zen 1, 128-bit NEON code on ARM chips with 64-bit ALUs). In the scenario that I'm envisioning, `-C target-cpu=native` on such a CPU should produce optimal code, and this is beyond `multiversion`'s current ability.

However, if you are saying that the runtime part of my proposal could be implemented as an improvement to the `multiversion` crate, rather than as a core feature of `core::simd`, this is a proposal I could get behind.

I'm not sure if `preferred_width()` can be implemented as a library though, it seems to me that this one may need to get in sync with compiler internals that are not currently exposed to libraries, and may therefore require direct language support.

**Comment by HadrienG2** [comment]
Maybe a code example would also help:

```rust
// Internally computes stuff using Simd<f32, WIDTH>
fn f32_simd_alg_impl_static<const WIDTH: usize>(input: &[f32]) -> f32 { /* ... */ }

// Static dispatch to a computation of the right width
//
// Good for no_std scenarios or scenarios where the complexity of
// dynamic dispatch is otherwise unwarranted (e.g. target CPU
// is known and -C target-cpu can be used).
//
fn f32_simd_alg_static(input: &[f32]) -> f32 {
    const WIDTH: usize = simd::preferred_width().unwrap_or(4);
    f32_simd_alg_impl_static::<WIDTH>(input)
}

// Identical to f32_simd_alg_impl_dynamic, attributes aside
#[multiversion]
#[clone(/* ... all interesting hardware targets for SIMD ... */)]
fn f32_simd_alg_impl_static<const WIDTH: usize>(input: &[f32]) -> f32 { /* ... */ }

// Dynamic dispatch to a computation of the right width
//
// Good for builds that must run optimally on a broad hardware
// base, in scenarios with an underlying OS to provide the
// required information. Could be autogenerated by multiversion.
// Only suitable for coarse-grained algorithms that can amortize
// the dynamic dispatch cost.
//
fn f32_simd_alg_dynamic(input: &[f32]) -> f32 {
    match simd::native_width().or(simd::preferred_width()).unwrap_or(4) {
        1 => f32_simd_alg_impl_dynamic::<1>(input),
        2 => f32_simd_alg_impl_dynamic::<2>(input),
        4 => f32_simd_alg_impl_dynamic::<4>(input),
        8 => f32_simd_alg_impl_dynamic::<8>(input),
        16 => f32_simd_alg_impl_dynamic::<16>(input),
        _ => f32_simd_alg_impl_dynamic::<4>(input),
    }
}
```

**Comment by calebzulawski** [comment]
It would be very difficult to add to `std::simd` since it requires knowing the target features of the specific function, but it's something I had considered adding to multiversion (which is aware of the available features).  Might be worth opening an issue there so I don't forget about it.

One of the benefits of `std::simd` is that even the vector length is portable, and it allows you to choose the length based on what's appropriate for your algorithm.  Vectors smaller than your native width may be inefficient, but oversized vectors are compiled as multiple native vectors.

**Comment by workingjubilee** [comment]
> Maybe a code example would also help:
> 

Yes, code examples for what you want to do, do always help! Thank you. The more "worked" the example the better.
It's not our first time seeing SIMD code, obv, but it can look surprisingly different for different use-cases.

At the moment, we actually do consider this to be something a library can handle. Yes, improving multiversion (or a crate which does something similar) is likely best. Unfortunately, while you are correct that it would likely be ideal to
> get in sync with compiler internals that are not currently exposed to libraries, and thus require direct language support.

This is not really something well-handled by the Rust compiler either at the moment, so the idea that there is much to sync with is unfortunately not quite accurate either. 🙃 The Rust ABI uses various hacks, currently, to try to prevent miscompilations, on the somewhat optimistic assumption that these hacks will generally be optimized away. rustc does not have a full understanding of architectures and architectural features and the nuances of call ABIs. But between `#[cfg(target_cpu)]`, `#[target_feature(enable)]`, and feature detection code, what you are interested in _can_ actually be implemented as a library. So, "this already exists... but some assembly may be required".

...I mean "putting pieces together" but literally some assembly language programming may be required if you want to pick the best thing to dispatch to based on CPUID, because yes, you are correct that
> I say ideally infaillible as this would be most useful to users and I am sure that the info can be found at runtime. But I'm not sure if for all instruction sets it can be found without resorting to microbenchmarking or looking up the CPU model identifier in a hardware database. If not, core::simd may understandably not want to take the burden of maintaining either a HW database or a binding to someone else's database.

To do this endeavor optimally would in fact result in maintaining a hardware database.

Some reasonable heuristics _can_ be offered, and there are things that can be improved, but we have been deliberately cagey about introducing multiversioning or exposing hardware architectural details directly in _this_ library. You may be interested in trying out the compiler's `-Ztune-cpu` option, also.

**Comment by HadrienG2** [comment]
So, my personal summary is that...

- The dynamic dispatch subset of this proposal should be moved to `multiversion` (or similar): https://github.com/calebzulawski/multiversion/issues/33 .
- The static dispatch subset could probably also be handled by `multiversion`'s no-std. But it will likely require support from rustc, and that should be brought up to rust-lang as a separate issue.

Thanks for the discussion, everyone!
