### ISSUE TITLE
missing mask8x4

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/portable-simd#301]
Is there a reason there's no `mask8x4` exposed? `i8x4` is and the API supports it.

I'm also curious why there's no `i/u8x2`

**Comment by calebzulawski** [comment]
In the end, we intend on the API supporting vectors of very long lengths (perhaps up to 32768), so we aren't going to add an alias for every supported vector.  That said, I don't think we've settled on a decision as to which aliases to have.  For example, should there be `u8x1`?

Regarding the mask alias, that's probably not intentional.
