### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by burrbull** [rust-lang/portable-simd#302]
Docs on https://doc.rust-lang.org/std/simd/index.html are significantly outdated

**Comment by programmerjake** [comment]
Those are the docs for whatever's packaged with the latest stable compiler.

If you want more up-to-date docs, look at the nightly docs:
https://doc.rust-lang.org/nightly/std/simd/index.html

The nightly docs are still somewhat out-of-date because portable-simd changes aren't merged into the main rust repo that quickly, stuff in portable-simd that hasn't been merged yet (as of writing):
https://github.com/rust-lang/portable-simd/compare/2e081db92aa3ee0a4563bc28ce01bdad5b1b2efd...master

**Comment by programmerjake** [comment]
The latest portable-simd docs are auto-generated and available here:
https://rust-lang.github.io/portable-simd/core_simd/
