### ISSUE TITLE
non-power-of-2 Simd types have wrong size

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/portable-simd#319]
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f4ee5c373508bcb37be6cda3bb627b87
```rust
#![feature(repr_simd)]
use core::alloc::Layout;
#[repr(simd)]
struct Simd<T, const N: usize>(pub [T; N]);

fn main() {
    assert_eq!(
        Layout::new::<Simd<i8, 3>>(),
        Layout::from_size_align(3, 1).unwrap()
    );
}
```

I expected to see this happen: run with no errors because `Simd<T, N>` types should be the same size as the corresponding array type `[T; N]` (something we unofficially agreed on iirc, but is not formally decided)

Instead, this happened:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size: 4, align: 4 (1 << 2) }`,
 right: `Layout { size: 3, align: 1 (1 << 0) }`', src/main.rs:7:5
```

### Meta

`rustc --version --verbose`:
```
<current nightly as of issue creation -- probably 2022-11-29 nightly>
```

`crate version in Cargo.toml`:
N/A

**Comment by programmerjake** [comment]
see also #63

**Comment by programmerjake** [comment]
see some previous discussion: https://rust-lang.zulipchat.com/#narrow/stream/257879-project-portable-simd/topic/Bytemuckable.20Simd/near/311734698

**Comment by programmerjake** [comment]
imho we should define layout such that `sizeof(Simd<T, N>) == sizeof([T; N])` and `alignof(Simd<T, N>) == gcd(alignof(T), llvm_alignof(Simd<T, N>)) >= alignof(T)`
or, if we don't want to depend on llvm, we could pick the largest power of two `<= sizeof([T; N])` such that no padding is required.

**Comment by programmerjake** [comment]
Note the changes to vector layout by @RalfJung in https://github.com/rust-lang/rust/commit/891a4da4f3cf99d5ee6413d9a6948031306179af are the exact opposite of what we probably want: that commit adds padding until size is divisible by alignment, what we probably want is to decrease alignment enough that we can enforce vectors are the exact same size as the corresponding array (usually means no padding, there could still be padding if the element type contains padding, portable-simd will presumably enforce that those element types aren't allowed but `repr(simd)` might allow them in the future)

**Comment by programmerjake** [comment]
> imho we should define layout such that `sizeof(Simd<T, N>) == sizeof([T; N])` and `alignof(Simd<T, N>) == gcd(alignof(T), llvm_alignof(Simd<T, N>)) >= alignof(T)`

now that I think about some more, gcd of aligns is wrong, instead we probably want `alignof(Simd<T, N>) == gcd(sizeof([T; N]), llvm_alignof(Simd<T, N>)) >= alignof(T)`

**Comment by calebzulawski** [comment]
I wonder, what's the motivation for that commit?  If it's absolutely necessary for some other reason, we could pretty easily add a new repr for portable SIMD.

**Comment by programmerjake** [comment]
> I wonder, what's the motivation for that commit? If it's absolutely necessary for some other reason, we could pretty easily add a new repr for portable SIMD.

I would assume it's for enforcing rust's rule that every type must have its size be divisible by its alignment. llvm doesn't enforce that rule, so relying on llvm to calculate layout for vectors can violate that rule.

**Comment by RalfJung** [comment]
My commit does not change layout at all, it just changes the layout consistency check, assuming that the existing layout code is right. If the existing layout code is buggy then yeah I also ported the bug to the layout checker now. Feel free to fix both at the same time. :) The important part is the the size and align of the type must be uniquely determined by the size and align of the vector elements and the number of elements.

**Comment by RalfJung** [comment]
The actual layout computation is [here](https://github.com/rust-lang/rust/blob/69df0f2c2f665d7f4e38a3579a81d4efc0d81034/compiler/rustc_ty_utils/src/layout.rs#L363-L366). And yes `size.align_to(align.abi)` is needed because size must be a multiple of align in Rust. So if you want 3-element SIMD vectors to not have trailing padding, then `vector_align` needs to be adjusted to return a lower alignment for these types.

This behavior of rustc (to round up vector sizes to the next power of two) has existed [at least since 2016](https://github.com/rust-lang/rust/commit/fe48a4af8403289ebc811884964fc4ef91f6bc09).

Cc @eddyb

**Comment by eddyb** [comment]
To be clear, this is not rustc-specific behavior but LLVM behavior - the reason we *have to* reuse the `datalayout` string is that mismatches between rustc and LLVM could lead to miscompilations if we have to use APIs where we assume LLVM is working with the same algorithms and configuration we are.

IIRC the logic is roughly:
* [`datalayout` string](https://llvm.org/docs/LangRef.html#data-layout) can contain an alignment for some exact vector size
* otherwise, the default is "natural alignment", i.e. the alignment is the same as the size (except rounded up to a power of two, if not already? I forget if it's meant to be stricter or not)

**Comment by eddyb** [comment]
Reading more of the discussion above, you really cannot talk about `llvm_alignof(Simd<T, N>)` *as if* it's different than the Rust alignment.

At the point where you start diverging in alignments from LLVM, you can no longer use primitive vector types and ~~have to wrap them in packed structs to decrease alignment~~... except the vector is already rounded up to a "plausible hardware size" by that point so the packed struct can no longer decrease the size!

You would probably need to "just" not use non-pow2 *LLVM vector types*, i.e. do not have `Abi::Vector` for such malformed `#[repr(simd)]` types. Or maybe they can still be used when by-value but great care must be taken around loading and storing - you effectively would need to generate e.g. 3 loads/stores to read/write to/from `<3 x T>` values (or weird FCA loads/stores of `[3 x T]` which LLVM would desugar).

Frankly, after what I've seen from GLSL (which has e.g. size=12 align=16 types that "eat" padding when used as fields!), my humble suggestion might be to ban these types instead of giving them magical semantics, since you generally can't "take back" the magic, even if you manage to make it work initially.

**Comment by programmerjake** [comment]
what i'm envisioning is using npot vectors by value (not in memory) just uses usual llvm semantics, whereas when loading/storing llvm allows specifying the alignment, which is where we would override it to use the rust abi alignment.
if llvm decides to store vectors in temporary memory variables, it's free to use whatever layout it pleases, since llvm is allowed to modify code using the as-if rule.

note that npot vectors are natively supported on some ISAs (e.g. SVE, RVV, and SimpleV)

**Comment by programmerjake** [comment]
for llvm npot vector loads/stores, afaict from reading the llvm language reference llvm guarantees that they will not load/store padding if the elements are an integer byte size (so not `i4` since that's 1/2 byte) and have no padding -- since it says [here](https://releases.llvm.org/15.0.0/docs/LangRef.html#vector-type) vector load/stores act the same as array load/stores when the element type is an integer byte size. so, no, we won't need multiple llvm load/store instructions to load/store npot vectors.

**Comment by programmerjake** [comment]
> Frankly, after what I've seen from GLSL (which has e.g. size=12 align=16 types that "eat" padding when used as fields!), my humble suggestion might be to ban these types instead of giving them magical semantics, since you generally can't "take back" the magic, even if you manage to make it work initially.

we shouldn't run into that particular problem since the proposed layouts will always have `size % align == 0` like any other rust type, they're basically arrays' layouts but with the align increased as close as possible to llvm's preferred align without introducing padding or violating `size % align == 0`

**Comment by workingjubilee** [comment]
> I expected to see this happen: run with no errors because Simd<T, N> types should be the same size as the corresponding array type [T; N] (something we unofficially agreed on iirc, but is not formally decided)

It is not actually my opinion that these values should be equal in all cases, actually? I believe `f32x4` on x86 should be natively 16-byte aligned. Unless you are talking about `f32x3` specifically.

> Frankly, after what I've seen from GLSL (which has e.g. size=12 align=16 types that "eat" padding when used as fields!), my humble suggestion might be to ban these types instead of giving them magical semantics, since you generally can't "take back" the magic, even if you manage to make it work initially.

We are strongly inclined to think we do not want byte-level padding in SIMD types, I think only a few murmurs have even discussed that possibility and largely in a negative light. We collectively average out to feeling a little dubious even about niches (or other forms of bit-level padding).

**Comment by programmerjake** [comment]
> > I expected to see this happen: run with no errors because Simd<T, N> types should be the same size as the corresponding array type [T; N] (something we unofficially agreed on iirc, but is not formally decided)
> 
> It is not actually my opinion that these values should be equal in all cases, actually? I believe `f32x4` on x86 should be natively 16-byte aligned. Unless you are talking about `f32x3` specifically.

power-of-2 sized vectors always matched their corresponding array size and my proposal doesn't change that. if we use the `gcd(size, llvm_align)` proposal then power-of-2 vectors' alignments should be entirely unchanged too (assuming there isn't a weird arch that decides i8x4 has align 16 or something). my proposal only changes non-power-of-2 vectors.

I should point out that I am explicitly *not* changing `std::arch` simd types' layout, those are defined by their corresponding arch (that said, since iirc all current `std::arch` vector types are power-of-2 types without padding, the `gcd(size, llvm_align)` proposal would leave them unaffected even if those `std::arch` types were defined using `std::simd` with the `gcd(size, llvm_align)` proposal.)
> 
> > We are strongly inclined to think we do not want byte-level padding in SIMD types,

so then you also agree we should change rustc's current vector layouts to never introduce padding bytes. this requires potentially reducing alignment for non-power-of-2 vectors in order to not violate the rust `size % align == 0` rule.

**Comment by programmerjake** [comment]
note that my proposal means that `slice::as_simd` can never panic, currently it has to verify that the provided vector type has no padding and panics if that fails, which is a major footgun.
https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.as_simd

**Comment by workingjubilee** [comment]
...That's not really a footgun, honestly, unless you write code that never actually tests the function ever, since the result must be monomorphized.

**Comment by calebzulawski** [comment]
In our docs we already repeatedly describe vectors as "basically arrays" so I do think it's a footgun if they have unusual layouts, in this function and elsewhere.

**Comment by programmerjake** [comment]
> ...That's not really a footgun, honestly, unless you write code that never actually tests the function ever, since the result must be monomorphized.

maybe not in the sense of unintentionally causing UB, but it is in the sense of writing a bunch of code generic over vector lengths and expecting it to work for any length...which could require re-architecting a bunch of code to fix.

**Comment by RalfJung** [comment]
> >  I expected to see this happen: run with no errors because Simd<T, N> types should be the same size as the corresponding array type [T; N] (something we unofficially agreed on iirc, but is not formally decided)
>
> It is not actually my opinion that these values should be equal in all cases, actually? I believe f32x4 on x86 should be natively 16-byte aligned. Unless you are talking about f32x3 specifically.

You were quoting a statement about the *size* but your reply talks about *alignment*. Looks to me like you are talkink past each other?

f32x4 on x86 can be 16-byte aligned and still have the same size as `[f32; 4]` without any problem.

**Comment by RalfJung** [comment]
> power-of-2 sized vectors always matched their corresponding array size and my proposal doesn't change that. if we use the gcd(size, llvm_align) proposal then power-of-2 vectors' alignments should be entirely unchanged too (assuming there isn't a weird arch that decides i8x4 has align 16 or something). my proposal only changes non-power-of-2 vectors.

Usually alignment of such types is not even something we can decide. What is their alignment in C? We pretty much have to use the same to be ABI compatible.

**Comment by bjorn3** [comment]
Only the types in `core::arch` need to be abi compatible right? There are `From` impls to convert between the `core::arch` types and `core::simd::Simd`, but nothing that converts references for one type to references for the other type.

**Comment by RalfJung** [comment]
That is assuming people won't declare their own SIMD types and expect them to be compatible with the equivalent def.n in C.

**Comment by programmerjake** [comment]
> Usually alignment of such types is not even something we can decide. What is their alignment in C? We pretty much have to use the same to be ABI compatible.

imho `Simd<T, N>` is not the same type as existing C simd types, it's something new, defined by Rust, so ABI compatibility isn't an issue, unless we want it to be, in which case we can provide same-layout guarantees for some types e.g. we might want to define `Simd<u32, 4>` on x86_64 to have the same layout as `__m128`, and to define `Simd<i32, 5>` to *not* match any corresponding `std::arch::x86_64` type.

**Comment by RalfJung** [comment]
Fair. But make sure this is documented well and brace yourselves for bug reports caused by any difference in ABI. ;)

Does C even have non-pot SIMD types, and if yes then how do their layouts look like?

**Comment by programmerjake** [comment]
> Does C even have non-pot SIMD types, and if yes then how do their layouts look like?

for x86_64, yes, but only in clang, not gcc (idk about icc or msvc):
```c
typedef unsigned short u16x3 __attribute__((vector_size(3 * sizeof(unsigned short))));
```

**Comment by workingjubilee** [comment]
> Fair. But make sure this is documented well and brace yourselves for bug reports caused by any difference in ABI. ;)

our 128-bit integers don't even match up with C!

> Does C even have non-pot SIMD types, and if yes then how do their layouts look like?

"Ad hoc." As @eddyb mentioned/implied, `f32x3` is weird and special in most C implementations of it, if there are any (and there are some, due to code attempting to cross the C<->GLSL boundary), such that it traumatizes a lot of C programmers enough they don't want to touch it. People won't be that surprised that yet another implementation has decided on yet another quirky variant, though they may be annoyed.

**Comment by RalfJung** [comment]
> our 128-bit integers don't even match up with C!

And that is such a success that you want to repeat it? :joy:

**Comment by RalfJung** [comment]
> for x86_64, yes, but only in clang, not gcc (idk about icc or msvc):

So what is their size and alignment?

**Comment by programmerjake** [comment]
https://gcc.godbolt.org/z/d1W8GPb1x

in x86_64 clang, u16x3 has size 8 align 8.

**Comment by programmerjake** [comment]
imho it's more important for portable simd to not have padding than to match clang's seemingly arbitrary decision (afaict they implemented gcc's vector syntax but didn't bother to restrict it to powers of 2 like gcc does and didn't specifically plan for any particular layout for the cases where clang supports sizes gcc doesn't) -- portable simd is intended for use in Rust, so avoiding footguns in Rust where simd types have weird padding is preferable.

**Comment by workingjubilee** [comment]
> 
> And that is such a success that you want to repeat it? :joy: 

It's more "oh, don't worry, everyone trying to wield a `vec3` already knows they are deeply, insanely cursed, and so they'll be ready for madness to happen". When implemented in a way that matches GLSL's reprs (and not C's), an `f32x3` would be considered to be aligned to 16 bytes, but actually be size 12, in effect, i.e. the compiler is allowed to pack a float after it during layout. So code translating across the boundaries has to reason about that.

Obviously "working with data before then passing it into a uniform buffer" is not the only use case of SIMD but it's one which sees a lot of action, so the expectations in this area are already a bit damned. In other words, C is not the only accursed ABI to think about here.

**Comment by eddyb** [comment]
Alright this was a bit painful to encode in LLVM IR but [here's an experiment](https://godbolt.org/z/n9MW89hvK) so we can see what's going on:
```llvm
define ptr @add_one_i32x3(ptr %p) {
    %p_plus_one_i32x3 = getelementptr <3 x i32>, ptr %p, i32 1
    ret ptr %p_plus_one_i32x3
}

define <3 x i32> @load_i32x3_unaligned(ptr %p) {
    %v = load <3 x i32>, ptr %p, align 1
    ret <3 x i32> %v
}
```
```asm
add_one_i32x3:                          # @add_one_i32x3
        lea     rax, [rdi + 16]
        ret
load_i32x3_unaligned:                   # @load_i32x3_unaligned
        movsd   xmm0, qword ptr [rdi]           # xmm0 = mem[0],zero
        movss   xmm1, dword ptr [rdi + 8]       # xmm1 = mem[0],zero,zero,zero
        shufps  xmm1, xmm0, 48                  # xmm1 = xmm1[0,0],xmm0[3,0]
        shufps  xmm0, xmm1, 132                 # xmm0 = xmm0[0,1],xmm1[0,2]
        ret
```

Good news: `load_i32x3_unaligned` behaves as you'd expect, only reading 12 bytes, as `qword`(8)+`dword`(4).
This would suggest `<3 x i32>` has an "inherent/data" size of 12 bytes (similar to how `i96` works?).

Bad news: `add_one_i32x3` adds 16 bytes to the pointer, which is *not* what you want.
This would suggest `<3 x i32>` has a "stride" of 16 bytes (i.e. rounded up to the next power of 2).

Given this I don't think I can in good conscience recommend messing around with `Abi::Vector`.

What you *could* do is add a `#[repr(compact_simd)]` ("packed" seems ambiguous but I basically mean "decrease alignment to the largest value that does not result in padding"), and then have layout logic pick:
* `Abi::Vector` wherever possible
* `Abi::CompactedVector` (a new variant which would have to be added)
  * for LLVM, this would need to use the memory/immediate split that exists for `bool`
    (note: "immediate" below basically means "SSA value", i.e. "in a register" except more abstract)
    * when in memory: `bool` is `i8` and `i32x3` would have to be `[3 x i32]` (if we need the type at all)
    * as "immediate": `bool` is `i1` and `i32x3` could be `<3 x i32>` (allowing all vector opts etc.)
    * memory->immediate (reading): the memory type is `load`ed before being converted
      * this is fine for `bool` (where the conversion is a `i8`->`i1` `trunc`ation), but loading a `[3 x i32]` seems like a bad time
    * immediate->memory (writing): the immediate type is converted and then `store`d
      * again, this would require creating an array value (which likely lowers to 3 `i32` `store`s)

We could/should even make the normal `#[repr(simd)]` disallow or warn when it encounters cases involving padding, instead of giving the user the padded type.

Now, it might be easier than the complication above, if I go back to (sorry it got delayed so much...):
* https://github.com/rust-lang/rust/pull/98615

*However*, I do not have *strong* confidence that *nothing anywhere* would *ever* do a GEPi on a vector type like `<3 x i32>` - while we can *theoretically* remove most uses of LLVM struct/array types, vector types like `<3 x i32>` will fundamentally have to stick around (for the "immediate" aka SSA aka "in registers" side), and LLVM does not have a good way to *guarantee* that you're not using types *anywhere near memory*.

Or in other words, you want `rustc` to use the `<3 x i32>` LLVM type *but never let it* compute its stride of 16 bytes (to use in e.g. GEPi).

An easy example (even after https://github.com/rust-lang/rust/pull/98615, the PR linked above), is that a Rust slice type like `[i32x3]`, or even just calling `.add(1)` on a `*const i32x3`, will currently let LLVM use the stride of the type. At least `struct` fields only have constant offsets, but `.add(N)` would require us to *generate a multiplication* of the form `N * 12`, but *we don't do anything like that*.

At least the `Abi::CompactedVector` idea allows you to have a "split memory-vs-register semantics" type, *without* impacting anything that works with `#[repr(simd)]` today (which does need the larger alignment to be compatible with LLVM, at least for now).

**Comment by programmerjake** [comment]
> An easy example (even after [rust-lang/rust#98615](https://github.com/rust-lang/rust/pull/98615), the PR linked above), is that a Rust slice type like `[i32x3]`, or even just calling `.add(1)` on a `*const i32x3`, will currently let LLVM use the stride of the type. At least `struct` fields only have constant offsets, but `.add(N)` would require us to _generate a multiplication_ of the form `N * 12`, but _we don't do anything like that_.

hmm, it seems obvious to just use `[T; N]` anywhere we need GEP on `CompactVector`...let llvm convert to multiplication when needed (generally in instruction selection). basically, if we need to use `[i32x3]`, the type given to llvm would really be `[[i32; 3]]`, since it's for GEP so needs the in-memory layout.

**Comment by eddyb** [comment]
> basically, if we need to use `[i32x3]`, the type given to llvm would really be `[[i32; 3]]`, since it's for GEP so needs the in-memory layout.

Alright, that is doable, but requires the `Abi::CompactedVector` plan where we opt into the backends using different types for memory and registers - while it could be determined dynamically based on "uses `Abi::Vector(elem, n)` but `align != dl.vector_align(elem, n)`", that's not cheap, but also having the check in more than one place feels very sketchy compared the `Abi` including this information.

The other option might be having a flag for this behavior in `Abi::Vector`, instead of the separate variant - curious what @RalfJung and @oli-obk think of either of these options (I've definitely been pushed more towards reducing fragility/inherent risk in the encodings, by them and others, heh).

**Comment by RalfJung** [comment]
I'm out of my depth here, I don't understand the tradeoffs involved well enough to judge the pros and cons.

I guess instead of having the same logic in many places we could have a shared helper on Abi that distinguishes "register type" and "memory type", but no idea how practical that is.

**Comment by programmerjake** [comment]
> I'm out of my depth here, I don't understand the tradeoffs involved well enough to judge the pros and cons. I guess instead of having the same logic in many places we could have a shared helper on Abi that distinguishes "register type" and "memory type", but no idea how practical that is.

imho it would be useful to also have a load/store type (value actually being passed to the load/store instruction):
comparison:
* bool
    * memory type: i8
    * register type: i1
    * store type: i8
    ```llvm
    %bool_ptr = getelementptr i8, ptr %bool_array_ptr, i64 %idx ; compute pointer using memory type
    %v = zext i1 %bool_value to i8 ; convert register type to store type
    store i8 %v, ptr %bool_ptr ; store using store type
    ```
* Simd<i32, 3>
    * memory type: [3 x i32]
    * register type: <3 x i32>
    * store type: <3 x i32> with load/store ops' align being explicitly specified
    ```llvm
    %vec_ptr = getelementptr [3 x i32], ptr %vec_array_ptr, i64 %idx ; compute pointer using memory type
    ; register type is store type, no conversion needed
    store <3 x i32> %vec_value, ptr %vec_ptr, align 4 ; store using store type with alignment overridden to rust type alignment
    ```

**Comment by bjorn3** [comment]
The existing handling for handling bools being i1 in registers touches a lot of code (including seemingly unrelated code like determining signs for tags in the discriminant calculation code) and requires separate "immediate" and non-immediate versions of several methods. I am pretty sure the wrong one is used at several places. Also for Cranelift it did require extra special cases to handle "i1" being 8 bits big as Cranelift only has i8 and up. I believe GCC also requires special code as it uses a true bool type rather than a 1bit integer. Honestly I did prefer to just convert i1 to i8 as soon as possible and never pass it around as immediate. I realize this may not be possible for performance reasons though.

**Comment by programmerjake** [comment]
somewhat related: https://discourse.llvm.org/t/status-of-geps-into-vectors-of-overaligned-elements/67497/4?u=programmerjake

**Comment by programmerjake** [comment]
note that the alignment specification I'm proposing will allow arbitrary vector type punning without having alignment issues as long as the type pun is otherwise valid and llvm_align doesn't do crazy stuff (e.g. if llvm decides alignof(i8x4) is less than alignof(i32x1) for some strange reason): see https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/347#issuecomment-1442584902 for full explanation

**Comment by calebzulawski** [comment]
Considering this practically rather than idealistically for a moment, it's questionable to me whether it's really worth fixing the layout vs considering other options.  `bool` is perhaps the most frequently used primitive, whereas `std::simd` is niche, and non-PoT vectors considerably more niche.  Embedding a split memory/register repr throughout the compiler seems impractical and even if we decided that was the best option, I genuinely doubt anyone would ever implement it.

That said, not supporting non-PoT vectors could excessively complicate our API and perhaps delay stabilization while we try to sort out a simpler alternative to `SupportedLaneCount` (see #364).  I think it might be worth exploring other options that would give us non-PoT vectors in a more practical way.  I've thought of 3 alternatives:

* **Leave things as they are**.  The current implementation of non-PoT vectors works.  We could leave them be and use either an assert or non-local error in functions like `[T]::as_simd`.  This would leave us with the option of reducing the alignment in the future (maybe across an edition change).
* **Add a new `CompactSimd` or `UnalignedSimd` type.**  This type could implement all of the same functions and traits as `Simd`, but have a lesser alignment, either `repr(Rust)` or `repr(compact_simd)`.  To avoid a split memory/register repr, I would *not* make the type a vector type, but instead convert it to a `repr(simd)` type before passing it to the existing `simd_*` intrinsics.  We could easily implement `Into<Simd> for CompactSimd` and perhaps `Deref<Target = UnalignedSimd> for Simd`.  `[T]::as_simd` could still error, but have a matching `[T]::as_compact_simd` that works for any number of elements.
* **Make Simd `repr(compact_simd)` and convert before using.** Like the previous example, but wrapped into one type.  We could add new intrinsics `simd_align` and `simd_unalign` that convert between `repr(simd)` and `repr(compact_simd)`, a no-op when alignments match.

Personally, I like the first or second alternative best.  LLVM seems to be able to generate pretty good code for non-PoT vectors, and I think messing with the alignment could cause problems.  The second option would allow the user to choose which is more important--having a flexible memory layout or reliable codegen that doesn't juggle layouts.

cc @programmerjake @scottmcm
