### ISSUE TITLE
Dot Product

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/portable-simd#79]
We should, eventually, support the dot product operations. They're part of sse4.1, but the operation is very simple to express in rust as a fallback if sse4.1 is not available.

**Comment by calebzulawski** [comment]
My understanding is that `dpps`/`vdpps` are pretty slow (even slower than the non-vectorized version) and not worth it.  LLVM doesn't seem to generate it even in obvious situations (unless I messed up the flags somewhere):

https://gcc.godbolt.org/z/v5adxs

Also worth noting that it changes the order of the horizontal sum from what you might have expected (which is why I added `reassoc` in the example above)

**Comment by Lokathor** [comment]
deeply unfortunate!

Let's leave this open for a while longer in case anyone else has some comments, and we can close it up in the general issue triage cycle.

**Comment by workingjubilee** [comment]
According to Agner's instruction tables, a few early Intel CPUs support {V}DPPS well, but in general it seems to be a red herring, with seemingly huge op and latency counts compared to just doing a bunch of FMAs (on processors where that's available).
